defaults: &defaults
  redis:
    :host: 127.0.0.1
    :port: 6379
    :db: 0
  resque:
    :host: 127.0.0.1
    :port: 6379
    :db: 1
  cache:
    :host: localhost
    :port: 6379
    :db: 2

development:
  <<: *defaults

production:
  <<: *defaults