# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b38aee9da7ab2bfb9e10637cf4d0fa9b642dc1a84f85ad42f4cfb182cfd231931beb8b50b79e5f7677555a41d9358aaf8f1a709ff1f350059ffde1dfe6b9074
  robin_api_url: http://robin8.cloudhub.io/api/v1
  robin_api_user: perfectial@aylien.com
  robin_api_pass: abcd1234
  google:
    :client_id: '411343306765-qaokd4h3f7tivl2oo423shd54k30a6eo.apps.googleusercontent.com'
    :client_secret: '356dA9S4y5IbB-WpIhcX06rh'
  facebook:
    :app_id: '1581983398705792'
    :app_secret: '35049632231f31ffe301af15b21ad218'
  twitter:
    :api_key: 'chfbNFBkf56gJT2BDzmCNNfgv'
    :api_secret: 'WJvtq91oZgvGIJQl33J8kprn4eeWRlCzj4qlYulAyzwuxKATS3'
  linkedin:
    :api_key: '75qazimsj55zfi'
    :api_secret: 'UqTqTg4UCTBxo33u'

test:
  secret_key_base: 110dfb851be877fea669a4bd53e865de4444769e3aa5d5c5750eba6e1f81c11bf36bdbe209859de602c7a8a5f7226b160365aaff600795ffdd7087500fc91e62
  robin_api_url: http://robin8.cloudhub.io/api/v1
  robin_api_user: perfectial@aylien.com
  robin_api_pass: abcd1234

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  robin_api_url: <%= ENV["ROBIN_API_URL"] %>
  robin_api_user: <%= ENV["ROBIN_API_USER"] %>
  robin_api_pass: <%= ENV["ROBIN_API_PASS"] %>
  google:
    :client_id: '912209437439-und79tfo5ptup4ggm4q0b1qbqj2cav0s.apps.googleusercontent.com'
    :client_secret: 'HuKhpmfeUM1TNE5CzQmcYDLy'
  facebook:
    :app_id: '420339794748110'
    :app_secret: 'a8a02193ddcb77a91d8035bd985b643a'
  twitter:
    :api_key: 'GLL8kddaJYP4wInVaNS3FHun7'
    :api_secret: 'Nqyt5RebcockL8oddRATMPgRhkP6FAgcHqxcsb1ivhm41JqJFf'
  linkedin:
    :api_key: '75s1i535irsxoq'
    :api_secret: 'GRA5rFo0xfBKLhIf'

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  robin_api_url: <%= ENV["ROBIN_API_URL"] %>
  robin_api_user: <%= ENV["ROBIN_API_USER"] %>
  robin_api_pass: <%= ENV["ROBIN_API_PASS"] %>
  google:
    :client_id: '912209437439-und79tfo5ptup4ggm4q0b1qbqj2cav0s.apps.googleusercontent.com'
    :client_secret: 'HuKhpmfeUM1TNE5CzQmcYDLy'
  facebook:
    :app_id: '420339794748110'
    :app_secret: 'a8a02193ddcb77a91d8035bd985b643a'
  twitter:
    :api_key: 'GLL8kddaJYP4wInVaNS3FHun7'
    :api_secret: 'Nqyt5RebcockL8oddRATMPgRhkP6FAgcHqxcsb1ivhm41JqJFf'
  linkedin:
    :api_key: '75s1i535irsxoq'
    :api_secret: 'GRA5rFo0xfBKLhIf'
