---
:concurrency: 60
:pidfile: tmp/pids/sidekiq.pid
production:
  :concurrency: 25
:queues:
  - [default, 10]
  - [campaign, 20]
  - [campaign_show, 10]
  - [phone_location, 40]
:limits:
  campaign_show: 1
