---
:concurrency: 4
:pidfile: tmp/pids/sidekiq.pid
production:
  :concurrency: 4
staging:
  :concurrency: 2
qa:
  :concurrency: 2
:queues:
  - [default, 10]
  - [message, 20] 
  - [campaign, 40]
  - [campaign_show, 20]
  - [campaign_observer_worker, 10]
  - [kol_influence_metrics_worker, 10]
:limits:
  campaign_show: 1
  kol_influence_metrics_worker: 2
