class AddColumnInfluenceScoreToKol < ActiveRecord::Migration
  def change
    add_column :kols, :influence_score, :float, :default => -1

    remove_column :kols,  "monetize_post"
    remove_column :kols,  "monetize_post_weibo"
    remove_column :kols,  "monetize_post_personal"
    remove_column :kols,  "monetize_post_public1st"
    remove_column :kols,  "monetize_post_public2nd"
    remove_column :kols,  "monetize_create"
    remove_column :kols,  "monetize_create_weibo"
    remove_column :kols,  "monetize_create_personal"
    remove_column :kols,  "monetize_create_public1st"
    remove_column :kols,  "monetize_create_public2nd"
    remove_column :kols,  "monetize_share"
    remove_column :kols,  "monetize_share_weibo"
    remove_column :kols,  "monetize_share_personal"
    remove_column :kols,  "monetize_share_public1st"
    remove_column :kols,  "monetize_share_public2nd"
    remove_column :kols,  "monetize_review"
    remove_column :kols,  "monetize_review_weibo"
    remove_column :kols,  "monetize_review_personal"
    remove_column :kols,  "monetize_review_public1st"
    remove_column :kols,  "monetize_review_public2nd"
    remove_column :kols,  "monetize_speech"
    remove_column :kols,  "monetize_speech_weibo"
    remove_column :kols,  "monetize_speech_personal"
    remove_column :kols,  "monetize_speech_public1st"
    remove_column :kols,  "monetize_speech_public2nd"
    remove_column :kols,  "monetize_event"
    remove_column :kols,  "monetize_focus"
    remove_column :kols,  "monetize_party"
    remove_column :kols,  "monetize_endorsements"
    remove_column :kols,  "monetize_interested_post"
    remove_column :kols,  "monetize_interested_create"
    remove_column :kols,  "monetize_interested_share"
    remove_column :kols,  "monetize_interested_review"
    remove_column :kols,  "monetize_interested_speech"
    remove_column :kols,  "monetize_interested_event"
    remove_column :kols,  "monetize_interested_focus"
    remove_column :kols,  "monetize_interested_party"
    remove_column :kols,  "monetize_interested_endorsements"
  end
end
