import mirrorCreator from 'mirror-creator';

const actionTypes = mirrorCreator([
  'FETCH_CAMPAIGNS', 'SAVE_CAMPAIGN',
  'FETCH_CAMPAIGN', 'UPDATE_CAMPAIGN', 'FETCH_INVITES_OF_CAMPAIGN',
  'FETCH_RECRUIT_CAMPAIGN', 'FETCH_APPLIES_OF_RECRUIT_CAMPAIGN', 'UPDATE_RECRUIT_CAMPAIGN_KOL_STATUS', 'UPDATE_RECRUIT_CAMPAIGN_KOLS',
  'FETCH_STATISTICS_CLICKS_OF_CAMPAIGN',
  'FETCH_BRAND_PROFILE', 'UPDATE_BRAND_PROFILE',
  'UPDATE_BRAND_PASSWORD'
]);

export default actionTypes;
