require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DraftPitchesController, type: :controller do

  # # This should return the minimal set of attributes required to create a valid
  # # DraftPitch. As you add validations to DraftPitch, be sure to
  # # adjust the attributes here as well.
  # let(:valid_attributes) {
  #   skip("Add a hash of attributes valid for your model")
  # }

  # let(:invalid_attributes) {
  #   skip("Add a hash of attributes invalid for your model")
  # }

  # # This should return the minimal set of values that should be in the session
  # # in order to pass any filters (e.g. authentication) defined in
  # # DraftPitchesController. Be sure to keep this updated too.
  # let(:valid_session) { {} }

  # describe "GET #index" do
  #   it "assigns all draft_pitches as @draft_pitches" do
  #     draft_pitch = DraftPitch.create! valid_attributes
  #     get :index, {}, valid_session
  #     expect(assigns(:draft_pitches)).to eq([draft_pitch])
  #   end
  # end

  # describe "GET #show" do
  #   it "assigns the requested draft_pitch as @draft_pitch" do
  #     draft_pitch = DraftPitch.create! valid_attributes
  #     get :show, {:id => draft_pitch.to_param}, valid_session
  #     expect(assigns(:draft_pitch)).to eq(draft_pitch)
  #   end
  # end

  # describe "GET #new" do
  #   it "assigns a new draft_pitch as @draft_pitch" do
  #     get :new, {}, valid_session
  #     expect(assigns(:draft_pitch)).to be_a_new(DraftPitch)
  #   end
  # end

  # describe "GET #edit" do
  #   it "assigns the requested draft_pitch as @draft_pitch" do
  #     draft_pitch = DraftPitch.create! valid_attributes
  #     get :edit, {:id => draft_pitch.to_param}, valid_session
  #     expect(assigns(:draft_pitch)).to eq(draft_pitch)
  #   end
  # end

  # describe "POST #create" do
  #   context "with valid params" do
  #     it "creates a new DraftPitch" do
  #       expect {
  #         post :create, {:draft_pitch => valid_attributes}, valid_session
  #       }.to change(DraftPitch, :count).by(1)
  #     end

  #     it "assigns a newly created draft_pitch as @draft_pitch" do
  #       post :create, {:draft_pitch => valid_attributes}, valid_session
  #       expect(assigns(:draft_pitch)).to be_a(DraftPitch)
  #       expect(assigns(:draft_pitch)).to be_persisted
  #     end

  #     it "redirects to the created draft_pitch" do
  #       post :create, {:draft_pitch => valid_attributes}, valid_session
  #       expect(response).to redirect_to(DraftPitch.last)
  #     end
  #   end

  #   context "with invalid params" do
  #     it "assigns a newly created but unsaved draft_pitch as @draft_pitch" do
  #       post :create, {:draft_pitch => invalid_attributes}, valid_session
  #       expect(assigns(:draft_pitch)).to be_a_new(DraftPitch)
  #     end

  #     it "re-renders the 'new' template" do
  #       post :create, {:draft_pitch => invalid_attributes}, valid_session
  #       expect(response).to render_template("new")
  #     end
  #   end
  # end

  # describe "PUT #update" do
  #   context "with valid params" do
  #     let(:new_attributes) {
  #       skip("Add a hash of attributes valid for your model")
  #     }

  #     it "updates the requested draft_pitch" do
  #       draft_pitch = DraftPitch.create! valid_attributes
  #       put :update, {:id => draft_pitch.to_param, :draft_pitch => new_attributes}, valid_session
  #       draft_pitch.reload
  #       skip("Add assertions for updated state")
  #     end

  #     it "assigns the requested draft_pitch as @draft_pitch" do
  #       draft_pitch = DraftPitch.create! valid_attributes
  #       put :update, {:id => draft_pitch.to_param, :draft_pitch => valid_attributes}, valid_session
  #       expect(assigns(:draft_pitch)).to eq(draft_pitch)
  #     end

  #     it "redirects to the draft_pitch" do
  #       draft_pitch = DraftPitch.create! valid_attributes
  #       put :update, {:id => draft_pitch.to_param, :draft_pitch => valid_attributes}, valid_session
  #       expect(response).to redirect_to(draft_pitch)
  #     end
  #   end

  #   context "with invalid params" do
  #     it "assigns the draft_pitch as @draft_pitch" do
  #       draft_pitch = DraftPitch.create! valid_attributes
  #       put :update, {:id => draft_pitch.to_param, :draft_pitch => invalid_attributes}, valid_session
  #       expect(assigns(:draft_pitch)).to eq(draft_pitch)
  #     end

  #     it "re-renders the 'edit' template" do
  #       draft_pitch = DraftPitch.create! valid_attributes
  #       put :update, {:id => draft_pitch.to_param, :draft_pitch => invalid_attributes}, valid_session
  #       expect(response).to render_template("edit")
  #     end
  #   end
  # end

  # describe "DELETE #destroy" do
  #   it "destroys the requested draft_pitch" do
  #     draft_pitch = DraftPitch.create! valid_attributes
  #     expect {
  #       delete :destroy, {:id => draft_pitch.to_param}, valid_session
  #     }.to change(DraftPitch, :count).by(-1)
  #   end

  #   it "redirects to the draft_pitches list" do
  #     draft_pitch = DraftPitch.create! valid_attributes
  #     delete :destroy, {:id => draft_pitch.to_param}, valid_session
  #     expect(response).to redirect_to(draft_pitches_url)
  #   end
  # end

end
